"""add converted_invoice_id to quotations

Revision ID: 01723ab4d4ef
Revises: 495ad3a1f74e
Create Date: 2026-07-14 22:26:07.971398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '01723ab4d4ef'
down_revision: Union[str, None] = '495ad3a1f74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('converted_invoice_id', app.models.mixins.GUID(), nullable=True))
    op.create_foreign_key(None, 'quotations', 'sales_invoices', ['converted_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'converted_invoice_id')
    # ### end Alembic commands ###
