"""add payment gateway transactions and gstr1 filings

Revision ID: 39b65b2328b9
Revises: ad81e36fceee
Create Date: 2026-07-11 05:54:58.846481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '39b65b2328b9'
down_revision: Union[str, None] = 'ad81e36fceee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstr1_filings',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('return_period', sa.String(length=6), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('gsp_reference', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'return_period', name='uq_gstr1_filing_org_period')
    )
    op.create_index(op.f('ix_gstr1_filings_organization_id'), 'gstr1_filings', ['organization_id'], unique=False)
    op.create_table('payment_gateway_transactions',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receipt_reference', sa.String(length=60), nullable=True),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('qr_image_url', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_reference')
    )
    op.create_index(op.f('ix_payment_gateway_transactions_organization_id'), 'payment_gateway_transactions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_gateway_transactions_organization_id'), table_name='payment_gateway_transactions')
    op.drop_table('payment_gateway_transactions')
    op.drop_index(op.f('ix_gstr1_filings_organization_id'), table_name='gstr1_filings')
    op.drop_table('gstr1_filings')
    # ### end Alembic commands ###
