"""add free_quantity to goods receipt items

Revision ID: 495ad3a1f74e
Revises: 93f371335923
Create Date: 2026-07-12 11:57:52.074114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '495ad3a1f74e'
down_revision: Union[str, None] = '93f371335923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'goods_receipt_items',
        sa.Column(
            'free_quantity', sa.Numeric(precision=14, scale=3, asdecimal=False),
            nullable=False, server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_receipt_items', 'free_quantity')
    # ### end Alembic commands ###
