"""add close_by to payment gateway transactions

Revision ID: 632a7f49ab4e
Revises: 39b65b2328b9
Create Date: 2026-07-11 06:31:26.880236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '632a7f49ab4e'
down_revision: Union[str, None] = '39b65b2328b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_gateway_transactions', sa.Column('close_by', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_gateway_transactions', 'close_by')
    # ### end Alembic commands ###
