"""add offline sync tables

Revision ID: 93f371335923
Revises: 632a7f49ab4e
Create Date: 2026-07-11 07:43:50.150849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '93f371335923'
down_revision: Union[str, None] = '632a7f49ab4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_change_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_change_log_entity_type'), 'sync_change_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_change_log_organization_id'), 'sync_change_log', ['organization_id'], unique=False)
    op.create_table('sync_terminals',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=200), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('organization_id', 'device_fingerprint', name='uq_sync_terminal_fingerprint')
    )
    op.create_index(op.f('ix_sync_terminals_branch_id'), 'sync_terminals', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sync_terminals_organization_id'), 'sync_terminals', ['organization_id'], unique=False)
    op.create_table('offline_sale_records',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('terminal_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('client_operation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('error_detail', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['sync_terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'client_operation_id', name='uq_offline_sale_idempotency')
    )
    op.create_index(op.f('ix_offline_sale_records_organization_id'), 'offline_sale_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_offline_sale_records_terminal_id'), 'offline_sale_records', ['terminal_id'], unique=False)
    op.create_table('sync_conflicts',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('terminal_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('offline_sale_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolution_notes', sa.String(length=500), nullable=True),
    sa.Column('resolved_by_user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offline_sale_id'], ['offline_sale_records.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['sync_terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_conflicts_organization_id'), 'sync_conflicts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_terminal_id'), 'sync_conflicts', ['terminal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_conflicts_terminal_id'), table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_organization_id'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    op.drop_index(op.f('ix_offline_sale_records_terminal_id'), table_name='offline_sale_records')
    op.drop_index(op.f('ix_offline_sale_records_organization_id'), table_name='offline_sale_records')
    op.drop_table('offline_sale_records')
    op.drop_index(op.f('ix_sync_terminals_organization_id'), table_name='sync_terminals')
    op.drop_index(op.f('ix_sync_terminals_branch_id'), table_name='sync_terminals')
    op.drop_table('sync_terminals')
    op.drop_index(op.f('ix_sync_change_log_organization_id'), table_name='sync_change_log')
    op.drop_index(op.f('ix_sync_change_log_entity_type'), table_name='sync_change_log')
    op.drop_table('sync_change_log')
    # ### end Alembic commands ###
