"""initial schema

Revision ID: 98fa6507e60b
Revises: 
Create Date: 2026-07-10 23:59:14.284273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '98fa6507e60b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('default_state_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('branches',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_branch_org_code')
    )
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_table('categories',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', 'parent_id', name='uq_category_org_name_parent')
    )
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.create_table('coupons',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_coupon_org_code')
    )
    op.create_index(op.f('ix_coupons_organization_id'), 'coupons', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('is_credit_customer', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loyalty_points_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'phone', name='uq_customer_org_phone')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('hsn_codes',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_hsn_org_code')
    )
    op.create_index(op.f('ix_hsn_codes_organization_id'), 'hsn_codes', ['organization_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('narration', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_organization_id'), 'journal_entries', ['organization_id'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_ledger_account_org_code')
    )
    op.create_index(op.f('ix_ledger_accounts_organization_id'), 'ledger_accounts', ['organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_role_org_name')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('payable_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_supplier_org_name')
    )
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_uom_org_code')
    )
    op.create_index(op.f('ix_units_of_measure_organization_id'), 'units_of_measure', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('details', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('gift_cards',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('card_number', sa.String(length=40), nullable=False),
    sa.Column('initial_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_to_customer_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_to_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'card_number', name='uq_gift_card_org_number')
    )
    op.create_index(op.f('ix_gift_cards_organization_id'), 'gift_cards', ['organization_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('entry_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('account_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('category_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('hsn_code_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('uom_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tracks_batches', sa.Boolean(), nullable=False),
    sa.Column('tracks_serials', sa.Boolean(), nullable=False),
    sa.Column('tracks_expiry', sa.Boolean(), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_combo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['hsn_code_id'], ['hsn_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'barcode', name='uq_product_org_barcode'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_product_org_sku')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('supplier_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_purchase_orders_branch_id'), 'purchase_orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('quotations',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('customer_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('quotation_number', sa.String(length=40), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    op.create_index(op.f('ix_quotations_branch_id'), 'quotations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_quotations_organization_id'), 'quotations', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('permission_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('shifts',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_closing_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('counted_closing_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_variance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_branch_id'), 'shifts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    op.create_table('tax_rates',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('hsn_code_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['hsn_code_id'], ['hsn_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rates_hsn_code_id'), 'tax_rates', ['hsn_code_id'], unique=False)
    op.create_index(op.f('ix_tax_rates_organization_id'), 'tax_rates', ['organization_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('role_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'branch_id', name='uq_user_role_branch')
    )
    op.create_index(op.f('ix_user_roles_branch_id'), 'user_roles', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'code', name='uq_warehouse_branch_code')
    )
    op.create_index(op.f('ix_warehouses_branch_id'), 'warehouses', ['branch_id'], unique=False)
    op.create_table('combo_components',
    sa.Column('combo_product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('component_product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['combo_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_components_combo_product_id'), 'combo_components', ['combo_product_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('purchase_order_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('warehouse_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('supplier_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('grn_number', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=60), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grn_number')
    )
    op.create_index(op.f('ix_goods_receipts_organization_id'), 'goods_receipts', ['organization_id'], unique=False)
    op.create_table('product_batches',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('manufactured_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_number', name='uq_batch_product_number')
    )
    op.create_index(op.f('ix_product_batches_expiry_date'), 'product_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_product_batches_organization_id'), 'product_batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_batches_product_id'), 'product_batches', ['product_id'], unique=False)
    op.create_table('product_serials',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('warehouse_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'serial_number', name='uq_serial_product_number')
    )
    op.create_index(op.f('ix_product_serials_organization_id'), 'product_serials', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_serials_product_id'), 'product_serials', ['product_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('quotation_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('sales_invoices',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('customer_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('shift_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=False),
    sa.Column('is_inter_state', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cess_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_credit_sale', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('loyalty_points_earned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loyalty_points_redeemed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_sales_invoices_branch_id'), 'sales_invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_organization_id'), 'sales_invoices', ['organization_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=40), nullable=False),
    sa.Column('source_warehouse_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('destination_warehouse_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_index(op.f('ix_stock_transfers_organization_id'), 'stock_transfers', ['organization_id'], unique=False)
    op.create_table('gift_card_transactions',
    sa.Column('gift_card_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('amount_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gift_card_id'], ['gift_cards.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_card_transactions_gift_card_id'), 'gift_card_transactions', ['gift_card_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('goods_receipt_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_goods_receipt_id'), 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('customer_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('points_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_customer_id'), 'loyalty_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_organization_id'), 'loyalty_transactions', ['organization_id'], unique=False)
    op.create_table('payments',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('shift_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_table('sales_invoice_items',
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('hsn_code_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['hsn_code_id'], ['hsn_codes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_invoice_items_invoice_id'), 'sales_invoice_items', ['invoice_id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('branch_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('original_invoice_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('exchange_invoice_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('return_number', sa.String(length=40), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('refund_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_mode', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['exchange_invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_index(op.f('ix_sales_returns_branch_id'), 'sales_returns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_organization_id'), 'sales_returns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_original_invoice_id'), 'sales_returns', ['original_invoice_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('warehouse_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'batch_id', name='uq_stock_warehouse_product_batch')
    )
    op.create_index(op.f('ix_stock_items_organization_id'), 'stock_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_items_product_id'), 'stock_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_items_warehouse_id'), 'stock_items', ['warehouse_id'], unique=False)
    op.create_table('stock_ledger_entries',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('warehouse_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_entries_organization_id'), 'stock_ledger_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_product_id'), 'stock_ledger_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_reference_id'), 'stock_ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_warehouse_id'), 'stock_ledger_entries', ['warehouse_id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('transfer_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('product_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('batch_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    op.create_table('sales_return_items',
    sa.Column('sales_return_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('original_invoice_item_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['original_invoice_item_id'], ['sales_invoice_items.id'], ),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_items_sales_return_id'), 'sales_return_items', ['sales_return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_return_items_sales_return_id'), table_name='sales_return_items')
    op.drop_table('sales_return_items')
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_ledger_entries_warehouse_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_reference_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_product_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_organization_id'), table_name='stock_ledger_entries')
    op.drop_table('stock_ledger_entries')
    op.drop_index(op.f('ix_stock_items_warehouse_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_product_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_organization_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_sales_returns_original_invoice_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_organization_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_branch_id'), table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index(op.f('ix_sales_invoice_items_invoice_id'), table_name='sales_invoice_items')
    op.drop_table('sales_invoice_items')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_loyalty_transactions_organization_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_customer_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_goods_receipt_items_goods_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_gift_card_transactions_gift_card_id'), table_name='gift_card_transactions')
    op.drop_table('gift_card_transactions')
    op.drop_index(op.f('ix_stock_transfers_organization_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_sales_invoices_organization_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_branch_id'), table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_product_serials_product_id'), table_name='product_serials')
    op.drop_index(op.f('ix_product_serials_organization_id'), table_name='product_serials')
    op.drop_table('product_serials')
    op.drop_index(op.f('ix_product_batches_product_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_organization_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_expiry_date'), table_name='product_batches')
    op.drop_table('product_batches')
    op.drop_index(op.f('ix_goods_receipts_organization_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_combo_components_combo_product_id'), table_name='combo_components')
    op.drop_table('combo_components')
    op.drop_index(op.f('ix_warehouses_branch_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_branch_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tax_rates_organization_id'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_hsn_code_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_branch_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_quotations_organization_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_branch_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_branch_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_journal_lines_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_gift_cards_organization_id'), table_name='gift_cards')
    op.drop_table('gift_cards')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_of_measure_organization_id'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_ledger_accounts_organization_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index(op.f('ix_journal_entries_organization_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_hsn_codes_organization_id'), table_name='hsn_codes')
    op.drop_table('hsn_codes')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_coupons_organization_id'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
