"""add plans, subscriptions, password reset tokens

Revision ID: 9964fe50d368
Revises: 01723ab4d4ef
Create Date: 2026-07-15 00:59:11.056639

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = '9964fe50d368'
down_revision: Union[str, None] = '01723ab4d4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subscriptions',
    sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('plan_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_subscription_org')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Reference data: the 3 sellable tiers. Seeded here (not app/seed.py)
    # because signup must be able to look up a plan by code before any
    # organization -- and therefore before app/seed.py's org-exists guard
    # -- has ever run.
    plans_table = sa.table(
        'plans',
        sa.column('id', app.models.mixins.GUID()),
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('price_monthly', sa.Numeric),
        sa.column('max_branches', sa.Integer),
        sa.column('max_users', sa.Integer),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(plans_table, [
        {
            'id': uuid.uuid4(), 'code': 'starter', 'name': 'Starter', 'price_monthly': 999,
            'max_branches': 1, 'max_users': 3, 'is_active': True,
        },
        {
            'id': uuid.uuid4(), 'code': 'growth', 'name': 'Growth', 'price_monthly': 2999,
            'max_branches': 5, 'max_users': 15, 'is_active': True,
        },
        {
            'id': uuid.uuid4(), 'code': 'enterprise', 'name': 'Enterprise', 'price_monthly': 9999,
            'max_branches': None, 'max_users': None, 'is_active': True,
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###
