"""add coupon fields to sales invoice

Revision ID: ad81e36fceee
Revises: 98fa6507e60b
Create Date: 2026-07-11 05:29:27.256736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = 'ad81e36fceee'
down_revision: Union[str, None] = '98fa6507e60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoices', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column(
        'sales_invoices',
        sa.Column(
            'coupon_discount_amount', sa.Numeric(precision=12, scale=2, asdecimal=False),
            nullable=False, server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_invoices', 'coupon_discount_amount')
    op.drop_column('sales_invoices', 'coupon_code')
    # ### end Alembic commands ###
