"""add app_notifications table

Revision ID: b3f5a1c7d9e4
Revises: b3f5a1c7d9e3
Create Date: 2026-08-14 03:23:39.411874

"""
from typing import Sequence, Union

import sqlalchemy as sa

import app.models.mixins
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3f5a1c7d9e4'
down_revision: Union[str, None] = 'b3f5a1c7d9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'app_notifications',
        sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('user_id', app.models.mixins.GUID(), nullable=True),
        sa.Column('category', sa.String(length=30), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('body', sa.String(length=1000), nullable=True),
        sa.Column('reference_type', sa.String(length=30), nullable=True),
        sa.Column('reference_id', app.models.mixins.GUID(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_app_notifications_organization_id'), 'app_notifications', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_notifications_organization_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###
