"""add supplier_payments table

Revision ID: b3f5a1c7d9e3
Revises: b3f5a1c7d9e2
Create Date: 2026-08-14 03:12:41.994949

"""
from typing import Sequence, Union

import sqlalchemy as sa

import app.models.mixins
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3f5a1c7d9e3'
down_revision: Union[str, None] = 'b3f5a1c7d9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'supplier_payments',
        sa.Column('organization_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('supplier_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('method', sa.String(length=20), nullable=False),
        sa.Column('reference', sa.String(length=120), nullable=True),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('note', sa.String(length=255), nullable=True),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id']),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_organization_id'), 'supplier_payments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payments_organization_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
