from __future__ import annotations

from typing import Protocol

from sync_agent.domain.entities import (
    AuditEntry,
    ConflictRecord,
    LocalCustomer,
    LocalProduct,
    LocalStockItem,
    OfflineSale,
    SyncJournalEntry,
)


class ProductLocalRepository(Protocol):
    def upsert(self, product: LocalProduct) -> None: ...
    def delete(self, product_id: str) -> None: ...
    def get(self, product_id: str) -> LocalProduct | None: ...
    def list_all(self) -> list[LocalProduct]: ...
    def count(self) -> int: ...


class CustomerLocalRepository(Protocol):
    def upsert(self, customer: LocalCustomer) -> None: ...
    def delete(self, customer_id: str) -> None: ...
    def get(self, customer_id: str) -> LocalCustomer | None: ...
    def list_all(self) -> list[LocalCustomer]: ...
    def count(self) -> int: ...


class StockLocalRepository(Protocol):
    def upsert(self, stock: LocalStockItem) -> None: ...
    def delete(self, stock_id: str) -> None: ...
    def get(self, stock_id: str) -> LocalStockItem | None: ...
    def quantity_on_hand(self, warehouse_id: str, product_id: str) -> float: ...
    def count(self) -> int: ...


class OfflineSaleQueueRepository(Protocol):
    def enqueue(self, sale: OfflineSale) -> None: ...
    def get(self, client_operation_id: str) -> OfflineSale | None: ...
    def list_pending(self, limit: int) -> list[OfflineSale]: ...
    def update_result(
        self,
        client_operation_id: str,
        status: str,
        invoice_id: str | None,
        conflict_id: str | None,
        error_detail: str | None,
    ) -> None: ...
    def count_pending(self) -> int: ...
    def count_by_status(self) -> dict[str, int]: ...


class CursorRepository(Protocol):
    def get_cursor(self, entity_type: str) -> int: ...
    def set_cursor(self, entity_type: str, value: int) -> None: ...


class ConflictLocalRepository(Protocol):
    def upsert(self, conflict: ConflictRecord) -> None: ...
    def list_open(self) -> list[ConflictRecord]: ...


class AuditLogRepository(Protocol):
    def append(self, action: str, detail: dict) -> None: ...
    def list_recent(self, limit: int) -> list[AuditEntry]: ...


class SyncJournalRepository(Protocol):
    """Crash-recovery bookkeeping for in-flight push/pull cycles."""

    def begin_cycle(self, cycle_type: str) -> SyncJournalEntry: ...
    def end_cycle(self, journal_id: str, success: bool) -> None: ...
    def find_incomplete_cycles(self) -> list[SyncJournalEntry]: ...
